# Generated by Django 3.2.3 on 2021-06-08 07:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('markets', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decorator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Decorator')),
                ('desc', models.TextField(null=True)),
                ('price', models.FloatField(default=0.0, null=True, verbose_name='DecoratorPrice')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='MenuCategory')),
                ('desc', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'MenuCategory',
                'verbose_name_plural': 'MenuCategories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Product')),
                ('main_image', models.ImageField(null=True, upload_to='images/products/', verbose_name='ProductImage')),
                ('desc', models.TextField(null=True)),
                ('price', models.FloatField(default=0.0, null=True, verbose_name='ProductPrice')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.menucategory', verbose_name='MenuCategory')),
                ('decorators', models.ManyToManyField(to='shops.Decorator', verbose_name='Decorators')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ShopName')),
                ('main_image', models.ImageField(null=True, upload_to='images/shops/', verbose_name='ShopImage')),
                ('desc', models.TextField(null=True)),
                ('promptpayIdentifier', models.CharField(max_length=13, null=True)),
                ('deliverName', models.CharField(max_length=100, null=True, verbose_name='Deliver Name')),
                ('deliverPhone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^\\d{9,10}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shops',
            },
        ),
        migrations.CreateModel(
            name='ShopCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ShopCategory')),
            ],
            options={
                'verbose_name': 'ShopCategory',
                'verbose_name_plural': 'ShopCategories',
            },
        ),
        migrations.CreateModel(
            name='ShopImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/shops/', verbose_name='ShopMoreImage')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop')),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='categories',
            field=models.ManyToManyField(related_name='ShopCategories', to='shops.ShopCategory'),
        ),
        migrations.AddField(
            model_name='shop',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markets.market', verbose_name='MarketID'),
        ),
        migrations.AddField(
            model_name='shop',
            name='shopOwner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.shopowner', verbose_name='ShopOwner'),
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/products/', verbose_name='ProductImage')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.product')),
            ],
        ),
        migrations.AddField(
            model_name='menucategory',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop'),
        ),
        migrations.AddField(
            model_name='decorator',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop'),
        ),
        migrations.CreateModel(
            name='CustomerFavoriteShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer', verbose_name='Customer_ID')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop', verbose_name='FavoriteShop')),
            ],
        ),
    ]
